home/urls.py
from django.urls import path

from . import views

""" 为什么在 urls.py 文件中设置 app_name
1. app_name 本身不会直接在代码中使用， 而是 Django 用 app_name 配合 namespace 来组织
URL 反向解析（如 {% url %} 或 reverse()）时使用的
2. app_name 用于 Django 识别 app 的 URL 名字空间
"""
app_name = 'app_name_of_home'

urlpatterns = [
    path('index/', views.index),
    path('query/', views.save_query_params_2json),
    path('body/', views.obtain_request_body),
    path('header/', views.explore_request_headers),
    path('files/', views.play_request_files),
    path('return-html/', views.return_html),
    path('return-json/', views.return_json),
    path('return-another-json/', views.return_another_json),
    path('return-picture/', views.return_picture),
    path('return-zip/', views.return_zip),
    path('return-mp4/', views.return_mp4),
    path('return-mp3/', views.return_mp3),
    # TODO name 是为每个 URL 路由起一个唯一的名字，用于反向解析 URL（即通过名字生成 URL 地址），不必硬编码 URL 路径
    path('return-gif/', views.return_gif, name='gif_v'),  # name is an alias of 'return-gif'
    path('redirect-outside/', views.redirect_outside),
    path('redirect-inside/', views.redirect_inside),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # TODO name 是为每个 URL 路由起一个唯一的名字，用于反向解析 URL（即通过名字生成 URL 地址），不必硬编码 URL 路径
    path('', views.index, name='index'),

    # TODO include 是 Django 提供的一个函数，用来引入其他模块的 URL 配置
    # goods.urls 表示导入 goods 这个 package 的 urls 模块(urls.py)
    # 'goods/' 表示给所有 goods 相关的 URL 加一个统一的前缀 goods/
    # namespace 是 URL 名称的命名空间，它是 Django 为了解决多 app 中 URL 名字冲突、方便反向解析设置的机制
    # namespace 机制需要 app_name 支持，每一个应用的 urls.py 中要定义 app_name 变量, app_name 的值是任意的
    path('goods/', include('goods.urls', namespace='goods_ns')),
    path('home/', include('home.urls', namespace='home_ns')),
    path('cookies/', include("cookies.urls", namespace='cookies_ns')),
    path('todo/', include('todo.urls', namespace='todo')),
    path('users/', include('users.urls', namespace='users')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:item_id>/', views.todo_item, name='todo_item'),
    path('set-session/', views.set_session, name='set_session'),
    path('get-session/', views.get_session, name='get_session'),
    path('add-todo-item/', views.add_todo_item, name='add_todo_item'),
]

todo/models.py
from django.db import models


class TodoItem(models.Model):
    item = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)

    # auto_now_add 设置为 True 的作用: 在调用 TodoItem.objects.create 方法创建对象时会自动设置 created_at 字段的值为当前时间
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    # auto_now 设置为 True 的作用: 每次调用实例的 save 方法的时候都会更新 updated_at 字段的值为当前时间
    # 使用 TodoItem.objects.create 方法创建一个实例时, 它会在内部先创建一个实例, 然后会调用实例的 save 方法将实例保存到数据库
    # 所以在使用 TodoItem.objects.create 创建对象时 updated_at 字段也会被设置为当前时间
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    def __str__(self):
        # 返回待办事项的内容作为字符串表示
        return self.item

todo/forms.py
from django import forms
from .models import TodoItem


class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem   # 表单是基于 TodoItem 模型的
        fields = ['item']  # 声明只用 TodoItem 模型里的 item 字段作为表单字段 

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotAllowed, JsonResponse, HttpResponse
from django.db import transaction
from .models import TodoItem
from .forms import TodoItemForm

import json


def index(request):
    """
    - GET  请求: 显示所有 todo items
    - POST 请求: 添加一个新的 todo item. 然后重定向, 发起一次新的 GET 请求 (POST/REDIRECT/GET 模式, 避免重复的 POST 请求)
    - 其他请求：返回 HTTP 405 Method Not Allowed 错误
    """
    if request.method == 'POST':
        item_text = request.POST.get('item')
        if item_text:
            # 防止 空字符串 或者 None 插入到数据库
            TodoItem.objects.create(item=item_text)
        # redirect 函数会生成一个 HTTP 302 重定向响应, 是实现 POST/Redirect/GET 模式的核心
        # 浏览器收到这个响应后，会自动发起一个新的 GET 请求到相应的 URL
        # 需要了解 HTTP 重定向的工作原理, 可以利用 wireshark 观察详细信息
        return redirect('todo:index')
    elif request.method == 'GET':
        items = TodoItem.objects.all().order_by('id')
        # render 函数拿到数据然后渲染模板，产生 HTML 响应
        # 第一个参数是 request 对象，第二个参数是模板文件路径，第三个参数是一个字典，包含要传递给模板的数据
        # 公式: template + data -> web page(HTML)
        return render(request, 'todo/index.html', {'items': items})
    else:
        return HttpResponseNotAllowed(['GET', 'POST'])


def todo_item(request, item_id):
    """
    - PUT 请求: 更新一个 todo item 的内容
    - DELETE 请求: 删除一个 todo item
    - GET 请求: 显示一个 todo item 的详情
    - 其他请求：返回 HTTP 405 Method Not Allowed 错误
    """

    # 若数据库中没有主键为 item_id 的 TodoItem 对象, 立即返回一个 HTTP 404 错误响应
    item = get_object_or_404(TodoItem, pk=item_id)
    if request.method == 'GET':
        return render(request, 'todo/detail.html', {'item': item})
    elif request.method == 'PUT':
        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
        item.item = data.get('item', item.item)
        item.completed = data.get('completed', item.completed)
        item.save()

        # 返回 JSON 响应，包含更新时间
        return JsonResponse({
            'success': True,
            'updated_at': item.updated_at.strftime('%m-%d %H:%M')
        })
    elif request.method == 'DELETE':
        with transaction.atomic():  # 确保删除操作的原子性
            item.delete()
        return HttpResponse(status=204)
    else:
        return HttpResponseNotAllowed(['GET', 'PUT', 'DELETE'])


def set_session(request):
    """
    设置用户的 session 数据
    """

    # 1. Django 的 SessionMiddleware 中间件 会根据 HTTP 请求头中的 Cookie 字段 来判断用户是否已经拥有 sessionid
    # 如果有, SessionMiddleware 会从数据库中django_session 表中查询该 session ID 对应的 session 数据

    # 2. 如果客户端没有携带名为 sessionid 的 Cookie, 只要视图中对 request.session 进行了写操作(如设置某个键值).
    # Django 就会自动创建一个新的 session ID, 并在响应中通过 Set-Cookie 字段将 sessionid 发送给客户端,
    # 同时将会话数据保存到服务器端(如数据库、缓存等 session 后端).

    # 3. 客户端在后续请求中会自动携带该 session ID, 从而实现会话保持.

    request.session['username'] = 'Guanjie Sun'
    request.session['email'] = 'guanjie.sun@outlook.com'
    return HttpResponse('Session set successfully!')


def get_session(request):
    """
    获取 session 数据
    如果客户端没有携带 session ID 或者是无效的 session ID, 那么 request.session 将是一个空字典
    如果客户端携带了有效的 session ID, 那么 request.session 将包含之前设置的 'username' 和 'email' 数据发送给客户端
    """
    username = request.session.get('username', 'Guest')
    email = request.session.get('email', 'No email set')
    return HttpResponse(f'Hello, {username}@{email}!')


def add_todo_item(request):
    """ 利用 Django 的表单系统来添加 todo item """
    if request.method == 'POST':
        # 浏览器的刷新（F5）行为 或 点击地址栏再按回车 是“重新发送上一次的请求”
            # 也就是说：
            # 如果这个页面是通过 GET 请求获得的 → 刷新会重新发 GET；
            # 如果这个页面是通过 POST 请求获得的（例如你刚提交了表单）→ 刷新会尝试重新发 POST！
        # 所以如果用户在添加待办事项后刷新页面，浏览器会重新发送 POST 请求
        # 这会导致重复添加同一个待办事项
        # 为了避免这种情况，可以在处理 POST 请求后重定向到 GET 请求
        # 这样浏览器就会发起新的 GET 请求，而不是重新发送 POST 请求
        # 这就是所谓的 POST/Redirect/GET 模式
        form = TodoItemForm(request.POST)
        if form.is_valid():
            form.save()
            # redirect 函数会生成一个 HTTP 302 重定向响应
            # 浏览器收到这个响应后，会自动发起一个新的 GET 请求到相应的 URL
            # 302 的作用就是“Post → Redirect → Get” 模式的核心
            return redirect('todo:add_todo_item')
    else:
        form = TodoItemForm()
    return render(request, 'todo/add_todo_item.html', {'form': form})

todo/templates/todo/add_todo_item.html
<!DOCTYPE html>
<html>
<head>
    <title>Add Todo</title>
</head>
<body>
    {% comment %} 使用views.add_todo_item 视图函数添加一个新的 todo item {% endcomment %}
    <h1>Add a new todo item~</h1>
    <form method="post" action="{% url 'todo:add_todo_item' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'todo:index' %}">Back to todo list</a>
</body>
</html>

todo/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Item Detail</title>
    <style>
        body {
            width: 800px;
            margin: 0 auto;
        }
        h1 {
            text-align: center;
        }
        table {
            width: 100%;
            text-align: center;
            font-size: 20px
        }
    </style>
</head>
<body>
    <h1>Details of item {{ item.id }}</h1>

    <table border="1" cellspacing="0" cellpadding="8">
        <colgroup>
            <col style="background-color: #aff0f0; " />
            <col style="background-color: #c3e6fa; " />
            <col style="background-color: #e2cbf2; " />
            <col style="background-color: #e2cbf2; " />
            <col style="background-color: #e2cbf2; " />
        </colgroup>
        <thead>
            <tr>
                <th>ID</th>
                <th>Item</th>
                <th>Completed</th>
                <th>Created at</th>
                <th>Updated at</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.item }}</td>
                <td>
                    {% if item.completed %}
                        Yes
                    {% else %}
                        No
                    {% endif %}
                </td>
                <td>
                    {{ item.created_at|date:"m-d H:i" }}
                </td>
                <td>
                    {{ item.updated_at|date:"m-d H:i" }}
                </td>
            </tr>
        </tbody>
    </table>
</body>
</html>

todo/templates/todo/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TODO LIST</title>
    <link href="{% static 'todo/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'todo/icon/favicon.ico' %}" rel="icon">
    <script src="{% static 'todo/js/script.js' %}" defer></script>
</head>

<body>

    <header>
        <h1>Todo List Powered by Django and PostgreSQL</h1>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'todo:index' %}">Homepage</a></li>
            <li><a href="https://docs.djangoproject.com/en/4.2/" target="_blank">Django Docs</a></li>
            <li><a href="https://go.dev/" target="_blank">Go Official Docs</a></li>
            <li><a href="https://www.python.org/doc/" target="_blank">Python Docs</a></li>
            <li><a href="https://developer.mozilla.org/en-US/" target="_blank">MDN</a></li>
            <li><a href="https://github.com/public-apis/public-apis" target="_blank">Public APIs</a></li>
        </ul>
    </nav>


    <main>
        <article>
            <form method="post" action="{% url 'todo:index' %}">
                {% csrf_token %}
                <p class="form-line">
                    <label for="item-text">Item:</label>
                    <input type="text" name="item" id="item-text" placeholder="Add a new task~" required>
                    <input type="submit" value="Submit" />
                </p>
            </form>

        {% comment %} <table border="1" cellspacing="0" cellpadding="8"> {% endcomment %}
        <table>
            <colgroup>
                <col style="background-color: #aff0f0; " />
                <col style="background-color: #c3e6fa; " />
                <col style="background-color: #e2cbf2; " />
                <col style="background-color: #ede6c5; " />
                <col style="background-color: #c9f5c9; " />
                <col style="background-color: #f5beba; " />
            </colgroup>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Item</th>
                    <th>Completion Status</th>
                    <th>Action</th>
                    <th>Created at</th>
                    <th>Updated at</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr data-id="{{ item.id }}">
                    <td>
                        <a href="{% url 'todo:todo_item' item.id %}" target="_blank">{{ item.id }}</a>
                    </td>
                    <td>{{ item.item }}</td>
                    <td>
                        {% comment %}
                        1. 如果已完成，则禁用两个 radio 按钮，用 input 元素的 disabled 属性实现
                        2. 基本逻辑: 
                        - 只能从未完成状态更新为已完成状态，不可能从已完成状态更新为未完成状态
                        - 创建 item 时，默认未完成状态
                        - 因此，只给 value='Yes'的 radio 按钮添加 onchange 属性，事件发生时用 updateCompletiondStatus 函数更新 item 的完成状态
                        {% endcomment %}
                        <label class='radio-label'>
                            <input
                            type="radio"
                            name="completion_status_{{ item.id }}"
                            value="Yes"
                            class="update-completion-status-btn"
                            data-id="{{ item.id }}"
                            {% if item.completed %}checked{% endif %}
                            {% if item.completed %}disabled{% endif %} 
                            >
                            <span>Yes</span>
                        </label>
                        <label class='radio-label'>
                            <input
                            type="radio"
                            name="completion_status_{{ item.id }}"
                            value="No"
                            {% if not item.completed %}checked{% endif %}
                            {% if item.completed %}disabled{% endif %}
                            >
                            <span>No</span>
                        </label>
                    </td>
                    <td>
                        <button class="delete-btn" data-id="{{ item.id }}">Delete</button>
                        <button class="update-btn" data-id="{{ item.id }}">Update</button>
                    </td>
                    <td>
                        {{ item.created_at|date:"m-d H:i" }}
                    </td>
                    <td>
                        {{ item.updated_at|date:"m-d H:i" }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </article>
    </main>
</body>
</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Todo List</title>
    <style>
    table {
        border-collapse: collapse;
        width: 30%;
    }
    th, td {
        border: 1px solid #ccc;
        text-align: center;
        padding: 8px;
    }
    th {
        background-color: #f4f4f4;
    }
    </style>
</head>
<body>
    <h1>Todo List</h1>

    <form method="post" action="{% url 'add_todo' %}">
        {% csrf_token %}
        <p>
            <label for="item_id">Item:</label>
            <input type="text" name="item" id="item_id" placeholder="Enter a new task" required>
        </p>
        <p>
            <button type="submit">Add</button>
        </p>
    </form>

    <h2>Todo items is shown as below:</h2>
        <table border="1" cellspacing="0" cellpadding="8">
            <colgroup>
                <col style="background-color: greenyellow; " />
                <col style="background-color: lightpink; " />
                <col style="background-color: lightblue; " />
            </colgroup>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Item</th>
                    <th>Completed</th>
                </tr>
            </thead>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.item }}</td>
                    <td>{% if item.completed %}✔️{% else %}❌{% endif %}</td>
                </tr>
                {% empty %}
                <!-- 如果items为空列表，则执行以下代码 -->
                <tr>
                    <td colspan="3">No todo items yet.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</body>
</html>